name: page_editor
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.4.0
  flutter_material_color_picker: ^1.2.0
  http: ^1.2.2
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  provider: ^6.1.2
  video_compress: ^3.1.3
  video_player: ^2.9.2
  wheel_slider: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
