name: map_backend
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  crypto: ^3.0.6
  csv: ^6.0.0
  dart_frog: ^1.1.0
  encrypt: ^5.0.3
  mongo_dart: ^0.10.4
  pointycastle: ^3.9.1
  yaml_writer: ^2.0.1

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.5
  very_good_analysis: ^5.1.0
